---
- name: "Generation du docker-compose file"
  template: 
    src: "docker-compose-Odoo.yml.j2"
    dest: /home/{{ ansible_user }}/docker-compose-Odoo.yml
    mode: 0655

- name: "deploy docker-compose-Odoo.yml"
  command: "docker-compose -f /home/{{ ansible_user }}/docker-compose-Odoo.yml up -d"
