apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    env: prod
  namespace: ic-group
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:7
          ports:
            - containerPort: 80
              name: postgresql
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: zaza
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-storage
      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pvc

