apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  labels:
    env: prod
  namespace: ic-group
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

