apiVersion: v1
kind: Service
metadata:
  name: ic-webapp
  namespace: ic-group

  labels:
    app: ic-webapp
    env: prod
spec:
  selector:
    app: ic-webapp
  type: NodePort
  ports:
    - name: ic-webapp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30006

