pgadmin_init_config_name: "pgAdmin4 Server"
pgadmin_init_config_group: "Servers"
pgadmin_init_config_username: "postgres"
pgadmin_init_config_host: "localhost"
pgadmin_init_config_SSLMode: "prefer"
pgadmin_init_config_maintenanceDB: "postgres"


