 all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod:
  children:
    client:
      children:
        ic_webapp:
          hosts:
            ic_webapp_server:
              ansible_host: 192.168.56.12
        odoo:
          hosts:
            odoo_server:
              ansible_host: 192.168.56.11
        pgadmin:
          hosts:
            pgadmin_server:
              ansible_host: 192.168.56.12
