all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
pgadmin_init_config_name: "pgAdmin4 Server"
pgadmin_init_config_group: "Servers"
pgadmin_init_config_username: "postgres"
pgadmin_init_config_host: "localhost"
pgadmin_init_config_SSLMode: "prefer"
pgadmin_init_config_maintenanceDB: "postgres"

prod:
  children:
    client:
      children:
        ic_webapp:
          hosts:
            ic_webapp_server:
              ansible_host: 192.168.56.12
        odoo:
          hosts:
            odoo_server:
              ansible_host: 192.168.56.11
        pgadmin:
          hosts:
            pgadmin_server:
              ansible_host: 192.168.56.12
