pipeline {
     environment {
       IMAGE_NAME = "static-website-example"
       IMAGE_TAG = "latest"
       DOCKERHUB_ID = "alexzaza"
       DOCKERHUB_PASSWORD = credentials('dockerhub_password')
       STAGING = "alexzaza-staging-fil-rouge"
       PRODUCTION = "alexzaza-production-fil-rouge"
     }
     agent none
     stages {
         stage('Build image') {
             agent any
             steps {
                script {
                  sh 'docker build --no-cache -f ./Jenkins-folders/${DOCKERFILE_NAME}-t alexzaza/$IMAGE_NAME:$IMAGE_TAG ./Jenkins-folders'
                }
             }
        }
        stage('Run container based on builded image') {
            agent any
            steps {
               script {
                 sh '''
                    echo "Cleaning existing container if exist"
                    docker ps -a | grep -i $IMAGE_NAME && docker rm -f ${IMAGE_NAME}
                    docker run --name $IMAGE_NAME -d -p 80:80 alexzaza/$IMAGE_NAME:$IMAGE_TAG
                    sleep 5
                 '''
               }
            }
       }
       stage('Test image') {
           agent any
           steps {
              script {
                sh '''
                    curl http://localhost | grep -i "200"
                '''
              }
           }
      }
      stage('Clean Container') {
          agent any
          steps {
             script {
               sh '''
                 docker stop $IMAGE_NAME
                 docker rm $IMAGE_NAME
               '''
             }
          }
     }
      stage ('Login and Push Image on docker hub') {  
        agent any
        steps {
          script {
            sh '''
                echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_ID --password-stdin
                docker push ${DOCKERHUB_ID}/$IMAGE_NAME:$IMAGE_TAG
               ''' 
          }
        } 
      }
       
    }    
}  
