apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    env: prod
  namespace: ic-group
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  labels:
    env: prod
  namespace: ic-group
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

