apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    env: prod
  namespace: ic-group
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

