all:
  children:
    prod:
      children:
        client:
          children:
            ic_webapp:
              hosts:
                ic_webapp_server:
                  ansible_host: 192.168.56.12
                  ansible_user: vagrant
                  ansible_ssh_pass: vagrant
                  ansible_ssh_private_key_file: /path/to/private/key
            odoo:
              hosts:
                odoo_server:
                  ansible_host: 192.168.56.11
                  ansible_user: vagrant
                  ansible_ssh_pass: vagrant
                  ansible_ssh_private_key_file: /path/to/private/key
            pgadmin:
              hosts:
                pgadmin_server:
                  ansible_host: 192.168.56.12
                  ansible_user: vagrant
                  ansible_ssh_pass: vagrant
                  ansible_ssh_private_key_file: /path/to/private/key

