apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    env: prod
  namespace: ic-group
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    app: pgadmin

